version: 2.1

orbs:
  unity: game-ci/unity@1.4.0

executors:
  unity/windows-2022:
    docker:
      - image: unityci/editor:windows-2022.3.1f1-universal-windows-platform-1.1.2
    resource_class: large

jobs:
  test-windows:
    executor: unity/windows-2022
    steps:
      - checkout
      - unity/test:
          context: unity
          executor:
            editor_version: 2022.3.1f1
            name: 'unity/windows-2022'
            resource_class: medium
            target_platform: 'windows-il2cpp'
          project-path: ''
          step-name: Check if the tests run and results are uploaded
          test-platform: editmode
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-password-var-name: UNITY_PASSWORD
          unity-username-var-name: UNITY_USERNAME

  build-Windows64-il2cpp:
    executor: unity/windows-2022
    steps:
      - checkout
      - unity/build:
          build-target: StandaloneWindows64
          compress: true
          context: unity
          executor:
            editor_version: 2022.3.1f1
          name: build-Windows64-il2cpp
          project-path: ''
          requires:
            - test-windows
          step-name: Build StandaloneWindows64 il2cpp
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-password-var-name: UNITY_PASSWORD
          unity-username-var-name: UNITY_USERNAME

workflows:
  build-and-test:
    jobs:
      - test-windows
      - build-Windows64-il2cpp:
          requires:
            - test-windows
